AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudWatch Monitoring for Pet Image Labeling System'

Parameters:
  SNSStackName:
    Type: String
    Description: Name of the SNS integration CloudFormation stack
    Default: pet-image-labeling-sns
  
  LambdaStackName:
    Type: String
    Description: Name of the Lambda functions CloudFormation stack
    Default: pet-image-labeling-functions
  
  S3StackName:
    Type: String
    Description: Name of the S3 storage CloudFormation stack
    Default: pet-image-labeling-storage
  
  DynamoDBStackName:
    Type: String
    Description: Name of the DynamoDB CloudFormation stack
    Default: pet-image-labeling-database

Resources:
  # Dashboard for monitoring the entire system
  SystemDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${AWS::StackName}-Dashboard"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${LambdaStackName}-GetImages" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", "FunctionName", "${LambdaStackName}-SubmitLabels" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", "FunctionName", "${LambdaStackName}-DashboardMetrics" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", "FunctionName", "${LambdaStackName}-GetUploadUrl" ],
                  [ ".", "Errors", ".", "." ],
                  [ ".", "Invocations", "FunctionName", "${LambdaStackName}-ImageUpload" ],
                  [ ".", "Errors", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Lambda Invocations and Errors",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "BucketSizeBytes", "BucketName", "${S3StackName}-pet-images-raw", "StorageType", "StandardStorage" ],
                  [ "...", "${S3StackName}-pet-images-processed", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "S3 Bucket Size",
                "period": 86400
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${DynamoDBStackName}-Images" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ],
                  [ ".", "ConsumedReadCapacityUnits", "TableName", "${DynamoDBStackName}-Labels" ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", "." ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Capacity Consumption",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/SNS", "NumberOfMessagesPublished", "TopicName", "${SNSStackName}-ImageUploads" ],
                  [ "...", "${SNSStackName}-LabelSubmissions" ],
                  [ "...", "${SNSStackName}-SystemAlerts" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "SNS Message Publishing",
                "period": 300
              }
            }
          ]
        }

  # Alarm for lambda error rates
  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-LambdaErrorRate"
      AlarmDescription: "Alarm when lambda functions have high error rates"
      MetricName: "Errors"
      Namespace: "AWS/Lambda"
      Dimensions:
        - Name: "FunctionName"
          Value: !Sub "${LambdaStackName}-ImageUpload"
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !ImportValue 
          'Fn::Sub': '${SNSStackName}-SystemAlertsTopicArn'

  # Alarm for high DynamoDB consumption
  DynamoDBConsumedCapacityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-DynamoDBHighConsumption"
      AlarmDescription: "Alarm when DynamoDB consumed capacity is high"
      MetricName: "ConsumedWriteCapacityUnits"
      Namespace: "AWS/DynamoDB"
      Dimensions:
        - Name: "TableName"
          Value: !Sub "${DynamoDBStackName}-Images"
      Statistic: "Sum"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !ImportValue 
          'Fn::Sub': '${SNSStackName}-SystemAlertsTopicArn'
  
  # Log group for application logs
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${AWS::StackName}-ApplicationLogs"
      RetentionInDays: 30

Outputs:
  DashboardURL:
    Description: "URL to the CloudWatch Dashboard"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${SystemDashboard}"
    
  LogGroupName:
    Description: "Name of the application log group"
    Value: !Ref ApplicationLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-LogGroupName"